on:
  push:
    paths:
      - "docs/**"
      - "*.md"

name: Publish

jobs:
  build:
    name: Check materials and publish if tagged
    runs-on: ubuntu-latest
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
      - name: QA check Markdown content
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
      - name: Run mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"
      - run: |
          mdbook build
      - name: Publish book website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          destination_dir: ./book
          keep_files: true
